### ISSUE TITLE
Date / version information

### ISSUE THREAD

**Issue by PeterMortensen** [jayliu50/qmk-cheatsheet#9]
I am missing information about what versions (and corresponding release dates) of QMK it applies to. As far as I know, some features (or the way they work) in QMK have been deprecated over time (and replaced by something else). It would help to judge if this document is out of date or not (and comparing to other sources of information).

Also, the document itself (as a web page) ought to have some date information (or at least a link to such information), like a publication date and last modified date (even if it is only meta tags in the HTML source with such information).

**Comment by jayliu50** [comment]
Hi @PeterMortensen, thank you for weighing in. As to the currency of the information, I'm unable to continually verify whether it's accurate and up-to-date with best practices, so I'll have to rely on the community to point out discrepancies. 

I could put a date on the footer, but I'm not sure what that would achieve, since I, myself, don't know what is the corresponding, actual modification date of the original. In the end, it will still require community members to point out updates that need to be made.

I know that's probably a lame answer, but I'm not (always) in a position to be keeping up with QMK's latest developments.

Curious to hear your thoughts.

**Comment by jayliu50** [comment]
https://github.com/jayliu50/qmk-cheatsheet/commit/1fea672f348596e1b451d9735748ceb2ba905b75
